/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Operaciones;
import Modelos.Historial;
import static Vista.Principal.user;
import java.util.Date;

/**
 *
 * @author ElíasRemedi
 */
public class GestionCadetes extends javax.swing.JFrame {

    /**
     * Creates new form GestionCadetes
     */
    Date fecha = new Date();
    Operaciones oper = new Operaciones();
    
    public GestionCadetes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarCadete = new javax.swing.JButton();
        jButtonEliminarCadete = new javax.swing.JButton();
        jButtonEditarCadete = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAgregarCadete.setText("Agregar Cadete");
        jButtonAgregarCadete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCadeteActionPerformed(evt);
            }
        });

        jButtonEliminarCadete.setText("Eliminar Cadete");
        jButtonEliminarCadete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCadeteActionPerformed(evt);
            }
        });

        jButtonEditarCadete.setText("Editar Cadete");
        jButtonEditarCadete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCadeteActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAgregarCadete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarCadete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarCadete, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonAgregarCadete)
                .addGap(32, 32, 32)
                .addComponent(jButtonEditarCadete)
                .addGap(31, 31, 31)
                .addComponent(jButtonEliminarCadete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarCadeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCadeteActionPerformed
        new Vista.AltaCadete().setVisible(true);
        this.dispose();
        
        fecha = new Date();
        Historial hist = new Historial(fecha, user, "Ingreso a Agregar Cadete");
        oper.altaReg(hist);
    }//GEN-LAST:event_jButtonAgregarCadeteActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
        new Vista.Principal().setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarCadeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCadeteActionPerformed
       new Vista.EditarCadete().setVisible(true);
       this.dispose();
       
        fecha = new Date();
        Historial hist = new Historial(fecha, user, "Ingreso a Editar Cadete");
        oper.altaReg(hist);
    }//GEN-LAST:event_jButtonEditarCadeteActionPerformed

    private void jButtonEliminarCadeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCadeteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarCadeteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarCadete;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditarCadete;
    private javax.swing.JButton jButtonEliminarCadete;
    // End of variables declaration//GEN-END:variables
}
