package Modelos;
// Generated 11-nov-2016 0:37:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cadetes generated by hbm2java
 */
public class Cadetes  implements java.io.Serializable {


     private int dni;
     private String nombre;
     private String apellido;
     private String direccion;
     private Integer telefono;
     private Set facturas = new HashSet(0);

    public Cadetes() {
    }

	
    public Cadetes(int dni) {
        this.dni = dni;
    }
    public Cadetes(int dni, String nombre, String apellido, String direccion, Integer telefono) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


