package Modelos;
// Generated 26-sep-2016 11:41:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cadetes generated by hbm2java
 */
public class Cadetes  implements java.io.Serializable {


     private Integer id;
     private Integer dni;
     private String nombre;
     private String apellido;
     private String direccion;
     private Integer telefono;
     private Set ticketCadetes = new HashSet(0);

    public Cadetes() {
    }

    public Cadetes(Integer dni, String nombre, String apellido, String direccion, Integer telefono) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
    }

    public Cadetes(Integer dni, String nombre, String apellido, String direccion, Integer telefono, Set ticketCadetes) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ticketCadetes = ticketCadetes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Set getTicketCadetes() {
        return this.ticketCadetes;
    }
    
    public void setTicketCadetes(Set ticketCadetes) {
        this.ticketCadetes = ticketCadetes;
    }




}


