package Modelos;
// Generated 29-sep-2016 15:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int telefono;
     private String nombre;
     private String apellido;
     private String direccion;
     private Boolean zona;
     private Set facturas = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int telefono) {
        this.telefono = telefono;
    }
    public Clientes(int telefono, String nombre, String apellido, String direccion, Boolean zona) {
       this.telefono = telefono;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.zona = zona;
    }
   
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Boolean getZona() {
        return this.zona;
    }
    
    public void setZona(Boolean zona) {
        this.zona = zona;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


