package Modelos;
// Generated 29-sep-2016 15:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comidas generated by hbm2java
 */
public class Comidas  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Float precioUnidad;
     private Set pedidos = new HashSet(0);

    public Comidas() {
    }

    public Comidas(String nombre, String descripcion, Float precioUnidad) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioUnidad = precioUnidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(Float precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


