package Modelos;
// Generated 26-sep-2016 11:41:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comidas generated by hbm2java
 */
public class Comidas  implements java.io.Serializable {

    public Comidas(String nombre, String descripcion, Float precioUnidad) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precioUnidad = precioUnidad;
    }


     private Integer id;
     private String nombre;
     private String descripcion;
     private Float precioUnidad;
     private Set facturaitemses = new HashSet(0);

    public Comidas() {
    }

    public Comidas(String nombre, String descripcion, Float precioUnidad, Set facturaitemses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioUnidad = precioUnidad;
       this.facturaitemses = facturaitemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(Float precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public Set getFacturaitemses() {
        return this.facturaitemses;
    }
    
    public void setFacturaitemses(Set facturaitemses) {
        this.facturaitemses = facturaitemses;
    }




}


