package Modelos;
// Generated 26-sep-2016 11:41:16 by Hibernate Tools 4.3.1



/**
 * Facturaitems generated by hbm2java
 */
public class Facturaitems  implements java.io.Serializable {


     private FacturaitemsId id;
     private Comidas comidas;
     private Factura factura;
     private Integer cantidad;

    public Facturaitems() {
    }

	
    public Facturaitems(FacturaitemsId id, Factura factura) {
        this.id = id;
        this.factura = factura;
    }
    public Facturaitems(FacturaitemsId id, Comidas comidas, Factura factura, Integer cantidad) {
       this.id = id;
       this.comidas = comidas;
       this.factura = factura;
       this.cantidad = cantidad;
    }
   
    public FacturaitemsId getId() {
        return this.id;
    }
    
    public void setId(FacturaitemsId id) {
        this.id = id;
    }
    public Comidas getComidas() {
        return this.comidas;
    }
    
    public void setComidas(Comidas comidas) {
        this.comidas = comidas;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


