package Modelos;
// Generated 26-sep-2016 11:41:16 by Hibernate Tools 4.3.1



/**
 * FacturaitemsId generated by hbm2java
 */
public class FacturaitemsId  implements java.io.Serializable {


     private int facturaId;
     private int numLinea;

    public FacturaitemsId() {
    }

    public FacturaitemsId(int facturaId, int numLinea) {
       this.facturaId = facturaId;
       this.numLinea = numLinea;
    }
   
    public int getFacturaId() {
        return this.facturaId;
    }
    
    public void setFacturaId(int facturaId) {
        this.facturaId = facturaId;
    }
    public int getNumLinea() {
        return this.numLinea;
    }
    
    public void setNumLinea(int numLinea) {
        this.numLinea = numLinea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaitemsId) ) return false;
		 FacturaitemsId castOther = ( FacturaitemsId ) other; 
         
		 return (this.getFacturaId()==castOther.getFacturaId())
 && (this.getNumLinea()==castOther.getNumLinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFacturaId();
         result = 37 * result + this.getNumLinea();
         return result;
   }   


}


