package Modelos;
// Generated 29-sep-2016 15:20:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idFactura;
     private Cadetes cadetes;
     private Clientes clientes;
     private Date fechaHora;
     private Boolean zona;
     private Float montoDeliv;
     private Float montoTotal;
     private Set pedidos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int idFactura) {
        this.idFactura = idFactura;
    }
     public Factura(int id, Cadetes cadetes, Clientes clientes, Date fechaHora, Boolean zona, Float montoDeliv, Float montoTotal) {
       this.idFactura = id;
       this.cadetes = cadetes;
       this.clientes = clientes;
       this.fechaHora = fechaHora;
       this.zona = zona;
       this.montoDeliv = montoDeliv;
       this.montoTotal = montoTotal;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public Cadetes getCadetes() {
        return this.cadetes;
    }
    
    public void setCadetes(Cadetes cadetes) {
        this.cadetes = cadetes;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Boolean getZona() {
        return this.zona;
    }
    
    public void setZona(Boolean zona) {
        this.zona = zona;
    }
    public Float getMontoDeliv() {
        return this.montoDeliv;
    }
    
    public void setMontoDeliv(Float montoDeliv) {
        this.montoDeliv = montoDeliv;
    }
    public Float getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Float montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


