package Modelos;
// Generated 26-sep-2016 11:41:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer id;
     private Double total;
     private Date fechaHora;
     private Boolean estadoFactura;
     private Integer clienteId;
     private Set ticketCadetes = new HashSet(0);
     private Set facturaitemses = new HashSet(0);

    public Factura() {
    }

    public Factura(Double total, Date fechaHora, Boolean estadoFactura, Integer clienteId, Set ticketCadetes, Set facturaitemses) {
       this.total = total;
       this.fechaHora = fechaHora;
       this.estadoFactura = estadoFactura;
       this.clienteId = clienteId;
       this.ticketCadetes = ticketCadetes;
       this.facturaitemses = facturaitemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Boolean getEstadoFactura() {
        return this.estadoFactura;
    }
    
    public void setEstadoFactura(Boolean estadoFactura) {
        this.estadoFactura = estadoFactura;
    }
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }
    public Set getTicketCadetes() {
        return this.ticketCadetes;
    }
    
    public void setTicketCadetes(Set ticketCadetes) {
        this.ticketCadetes = ticketCadetes;
    }
    public Set getFacturaitemses() {
        return this.facturaitemses;
    }
    
    public void setFacturaitemses(Set facturaitemses) {
        this.facturaitemses = facturaitemses;
    }




}


