package Modelos;
// Generated 11-nov-2016 0:37:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Date fechayHora;
     private Usuario usuario;
     private String descripcion;

    public Historial() {
    }

	
    public Historial(Date fechayHora) {
        this.fechayHora = fechayHora;
    }
    public Historial(Date fechayHora, Usuario usuario, String descripcion) {
       this.fechayHora = fechayHora;
       this.usuario = usuario;
       this.descripcion = descripcion;
    }
   
    public Date getFechayHora() {
        return this.fechayHora;
    }
    
    public void setFechayHora(Date fechayHora) {
        this.fechayHora = fechayHora;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


