package Modelos;
// Generated 11-nov-2016 0:37:55 by Hibernate Tools 4.3.1



/**
 * PedidoId generated by hbm2java
 */
public class PedidoId  implements java.io.Serializable {


     private int idFactura;
     private int idComida;

    public PedidoId() {
    }

    public PedidoId(int idFactura, int idComida) {
       this.idFactura = idFactura;
       this.idComida = idComida;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public int getIdComida() {
        return this.idComida;
    }
    
    public void setIdComida(int idComida) {
        this.idComida = idComida;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidoId) ) return false;
		 PedidoId castOther = ( PedidoId ) other; 
         
		 return (this.getIdFactura()==castOther.getIdFactura())
 && (this.getIdComida()==castOther.getIdComida());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFactura();
         result = 37 * result + this.getIdComida();
         return result;
   }   


}


