package Modelos;
// Generated 29-sep-2016 15:20:51 by Hibernate Tools 4.3.1



/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private PedidoId id;
     private Comidas comidas;
     private Factura factura;
     private Float totalParcial;
     private int cantidad;
     private Float precioXunidad;

    public Pedido() {
    }

	
    public Pedido(PedidoId id, Comidas comidas, Factura factura, int cantidad) {
        this.id = id;
        this.comidas = comidas;
        this.factura = factura;
        this.cantidad = cantidad;
    }
    public Pedido(Comidas comidas, Factura factura, int cantidad, Float precioXunidad) {
       
       PedidoId idp = new PedidoId();
       idp.setIdComida(comidas.getId());
       idp.setIdFactura(factura.getIdFactura());
       this.id = idp;
       this.comidas = comidas;
       this.factura = factura;
       this.totalParcial = precioXunidad*cantidad;
       this.cantidad = cantidad;
       this.precioXunidad = precioXunidad;
    }
   
    public PedidoId getId() {
        return this.id;
    }
    
    public void setId(PedidoId id) {
        this.id = id;
    }
    public Comidas getComidas() {
        return this.comidas;
    }
    
    public void setComidas(Comidas comidas) {
        this.comidas = comidas;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Float getTotalParcial() {
        return this.totalParcial;
    }
    
    public void setTotalParcial(Float totalParcial) {
        this.totalParcial = totalParcial;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Float getPrecioXunidad() {
        return this.precioXunidad;
    }
    
    public void setPrecioXunidad(Float precioXunidad) {
        this.precioXunidad = precioXunidad;
    }




}


