package Modelos;
// Generated 26-sep-2016 11:41:16 by Hibernate Tools 4.3.1



/**
 * TicketCadete generated by hbm2java
 */
public class TicketCadete  implements java.io.Serializable {


     private Integer id;
     private Cadetes cadetes;
     private Factura factura;
     private String zona;
     private String direccion;
     private Integer monto;

    public TicketCadete() {
    }

    public TicketCadete(Cadetes cadetes, Factura factura, String zona, String direccion, Integer monto) {
       this.cadetes = cadetes;
       this.factura = factura;
       this.zona = zona;
       this.direccion = direccion;
       this.monto = monto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cadetes getCadetes() {
        return this.cadetes;
    }
    
    public void setCadetes(Cadetes cadetes) {
        this.cadetes = cadetes;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }




}


