package Modelos;
// Generated 11-nov-2016 0:37:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombreUsuario;
     private String contrasenia;
     private Boolean gestionCadetes;
     private Boolean gestionMenu;
     private Boolean gestionClientes;
     private Boolean gestionEstadisticas;
     private Boolean gestionUsuarios;
     private Boolean gestionFacturacion;
     private Set historials = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Usuario(String nombreUsuario, String contrasenia, Boolean gestionCadetes,
            Boolean gestionMenu, Boolean gestionClientes, Boolean gestionEstadisticas, 
            Boolean gestionUsuarios, Boolean gestionFacturacion) {
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.gestionCadetes = gestionCadetes;
       this.gestionMenu = gestionMenu;
       this.gestionClientes = gestionClientes;
       this.gestionEstadisticas = gestionEstadisticas;
       this.gestionUsuarios = gestionUsuarios;
       this.gestionFacturacion = gestionFacturacion;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getGestionCadetes() {
        return this.gestionCadetes;
    }
    
    public void setGestionCadetes(Boolean gestionCadetes) {
        this.gestionCadetes = gestionCadetes;
    }
    public Boolean getGestionMenu() {
        return this.gestionMenu;
    }
    
    public void setGestionMenu(Boolean gestionMenu) {
        this.gestionMenu = gestionMenu;
    }
    public Boolean getGestionClientes() {
        return this.gestionClientes;
    }
    
    public void setGestionClientes(Boolean gestionClientes) {
        this.gestionClientes = gestionClientes;
    }
    public Boolean getGestionEstadisticas() {
        return this.gestionEstadisticas;
    }
    
    public void setGestionEstadisticas(Boolean gestionEstadisticas) {
        this.gestionEstadisticas = gestionEstadisticas;
    }
    public Boolean getGestionUsuarios() {
        return this.gestionUsuarios;
    }
    
    public void setGestionUsuarios(Boolean gestionUsuarios) {
        this.gestionUsuarios = gestionUsuarios;
    }
    public Boolean getGestionFacturacion() {
        return this.gestionFacturacion;
    }
    
    public void setGestionFacturacion(Boolean gestionFacturacion) {
        this.gestionFacturacion = gestionFacturacion;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }




}


